/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author USER
 */
public class KOMODITAS extends javax.swing.JFrame {

    /**
     * Creates new form KOMODITAS
     */
    
    DefaultTableModel KOM;
    public KOMODITAS() {
        initComponents();
        Connect();
        TabelKomoditas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        JUDUL_KOMODITAS = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Kode_Komoditas = new javax.swing.JTextField();
        Nilai_Ekspor = new javax.swing.JTextField();
        Pangsa_Total = new javax.swing.JTextField();
        Sektor_Komoditas = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        INSERT_KOM = new javax.swing.JButton();
        UPDATE_KOM = new javax.swing.JButton();
        DELETE_KOM = new javax.swing.JButton();
        CLEAR_KOM = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelKomoditas = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 153, 102));

        JUDUL_KOMODITAS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JUDUL_KOMODITAS.setForeground(new java.awt.Color(255, 255, 255));
        JUDUL_KOMODITAS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JUDUL_KOMODITAS.setText("DATA KOMODITAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JUDUL_KOMODITAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JUDUL_KOMODITAS, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Kode Komoditas");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Sektor Komoditas");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nilai Ekspor");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Pangsa Total");

        Kode_Komoditas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kode_KomoditasActionPerformed(evt);
            }
        });

        Sektor_Komoditas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PETERNAKAN", "PERTANIAN", "PERKEBUNAN", "PERHUTANAN", "PERIKANAN", "MINERBA", "MIGAS" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Kode_Komoditas)
                    .addComponent(Sektor_Komoditas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pangsa_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(Nilai_Ekspor, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(Kode_Komoditas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nilai_Ekspor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(Pangsa_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sektor_Komoditas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        INSERT_KOM.setText("INSERT");
        INSERT_KOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INSERT_KOMActionPerformed(evt);
            }
        });

        UPDATE_KOM.setText("UPDATE");
        UPDATE_KOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATE_KOMActionPerformed(evt);
            }
        });

        DELETE_KOM.setText("DELETE");
        DELETE_KOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETE_KOMActionPerformed(evt);
            }
        });

        CLEAR_KOM.setText("CLEAR");
        CLEAR_KOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEAR_KOMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(INSERT_KOM, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(UPDATE_KOM, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(DELETE_KOM, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(CLEAR_KOM, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DELETE_KOM, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(CLEAR_KOM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UPDATE_KOM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(INSERT_KOM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        TabelKomoditas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Komoditas", "Sektor Komoditas", "Nilai Ekspor", "Pangsa Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TabelKomoditas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelKomoditasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelKomoditas);

        jButton6.setBackground(new java.awt.Color(204, 51, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("CLOSE");
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 153, 102));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("MENU");
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    String url = "jdbc:sqlserver://192.168.43.36:1433;databaseName=SDAK5"; /*jadi ip address*/
    String user = "bytadit";
    String password = "bytadit123";
    
    Connection con;
    PreparedStatement pst;
    Statement st;
    ResultSet rs; 
    
    public void Connect()
    {
        try {
            con = DriverManager.getConnection(url, user, password);
        } catch (SQLException ex) {
            Logger.getLogger(KOMODITAS.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void TabelKomoditas()
    {
        try {
            pst = con.prepareStatement("SELECT * FROM KOMODITAS");
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData RSM = rs.getMetaData();
            int c;
            c = RSM.getColumnCount();
            
            KOM = (DefaultTableModel)TabelKomoditas.getModel();
            KOM.setRowCount(0);
            
            while(rs.next())
            {
                Vector v2 = new Vector();
                for(int i = 1; i <= c; i++)
                {
                    v2.add(rs.getString("Kode_Komoditas"));
                    v2.add(rs.getString("Sektor_Komoditas"));
                    v2.add(rs.getString("Nilai_Ekspor"));
                    v2.add(rs.getString("Pangsa_Total"));
                    
                }
                KOM.addRow(v2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(KOMODITAS.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void Kode_KomoditasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kode_KomoditasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Kode_KomoditasActionPerformed

    private void INSERT_KOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INSERT_KOMActionPerformed
        
        String Kode_Kom = Kode_Komoditas.getText();
        String Nil_Eks = Nilai_Ekspor.getText();
        String Sek_Kom = Sektor_Komoditas.getSelectedItem().toString();
        String Pang_Tot = Pangsa_Total.getText();
        
        
        try {
            pst = con.prepareStatement("INSERT INTO KOMODITAS VALUES (?,?,?,?)");
            pst.setString(1, Kode_Kom);
            pst.setString(2, Sek_Kom);
            pst.setString(3, Nil_Eks);
            pst.setString(4, Pang_Tot);
            
           
            int k = pst.executeUpdate();
            
            if (k==1)
            {
                JOptionPane.showMessageDialog(this,"Data Berhasil Ditambahkan");
                
                Kode_Komoditas.setText("");
                Sektor_Komoditas.setSelectedItem("");
                Nilai_Ekspor.setText("");
                Pangsa_Total.setText("");
                
                Kode_Komoditas.requestFocus();
                TabelKomoditas();
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Data Gagal Ditambahkan");
            }
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(KOMODITAS.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_INSERT_KOMActionPerformed

    private void TabelKomoditasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelKomoditasMouseClicked
        DefaultTableModel KOM = (DefaultTableModel)TabelKomoditas.getModel();
        
        int SelectIndex = TabelKomoditas.getSelectedRow();
        
        Kode_Komoditas.setText(KOM.getValueAt(SelectIndex, 0).toString());
        Pangsa_Total.setText(KOM.getValueAt(SelectIndex, 1).toString());
        Sektor_Komoditas.setSelectedItem(KOM.getValueAt(SelectIndex, 2).toString());
        Nilai_Ekspor.setText(KOM.getValueAt(SelectIndex, 3).toString());
        
        
        INSERT_KOM.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_TabelKomoditasMouseClicked

    private void UPDATE_KOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATE_KOMActionPerformed
        
        DefaultTableModel KOM = (DefaultTableModel)TabelKomoditas.getModel();
        int SelectIndex = TabelKomoditas.getSelectedRow();
        
        String Kode_Kom = Kode_Komoditas.getText();
        String Nil_Eks = Nilai_Ekspor.getText();
        String Sek_Kom = Sektor_Komoditas.getSelectedItem().toString();
        String Pang_Tot = Pangsa_Total.getText();
        
        
        try {
            pst = con.prepareStatement("UPDATE KOMODITAS SET Sektor_Komoditas = ?, Nilai_Ekspor = ?, Pangsa_Total = ? WHERE Kode_Komoditas = ?");
            
            pst.setString(1, Sek_Kom);         
            pst.setString(2, Nil_Eks);
            pst.setString(3, Pang_Tot);
            pst.setString(4, Kode_Kom);
            
            
            int k = pst.executeUpdate();
            
            if (k==1)
            {
                JOptionPane.showMessageDialog(this,"Data Berhasil Diperbarui");
                
                Kode_Komoditas.setText("");
                Sektor_Komoditas.setSelectedItem("");
                Nilai_Ekspor.setText("");
                Pangsa_Total.setText("");
                
                Kode_Komoditas.requestFocus();
                TabelKomoditas();
                INSERT_KOM.setEnabled(false);
                
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Data Gagal Diperbarui");
            }
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(KOMODITAS.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_UPDATE_KOMActionPerformed

    private void DELETE_KOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETE_KOMActionPerformed
        
        DefaultTableModel KOM = (DefaultTableModel)TabelKomoditas.getModel();
        int SelectIndex = TabelKomoditas.getSelectedRow();
        
        
        String Kode_Kom = Kode_Komoditas.getText();
        
        try {
            pst = con.prepareStatement("DELETE FROM KOMODITAS WHERE Kode_Komoditas = ?");
            
            pst.setString(1, Kode_Kom);
            
            int k = pst.executeUpdate();
            
            if (k==1)
            {
                JOptionPane.showMessageDialog(this,"Data Berhasil Dihapus");
                
                Kode_Komoditas.setText("");
                Sektor_Komoditas.setSelectedItem("");
                Nilai_Ekspor.setText("");
                Pangsa_Total.setText("");
                
                Kode_Komoditas.requestFocus();
                TabelKomoditas();
                INSERT_KOM.setEnabled(false);

                Kode_Komoditas.setEnabled(true);
                
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Data Gagal Dihapus");
            }
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(KOMODITAS.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_DELETE_KOMActionPerformed

    private void CLEAR_KOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEAR_KOMActionPerformed
        
                Kode_Komoditas.setText("");
                Sektor_Komoditas.setSelectedItem("");
                Nilai_Ekspor.setText("");
                Pangsa_Total.setText("");
                
                Kode_Komoditas.requestFocus();
                INSERT_KOM.setEnabled(false);
                TabelKomoditas();        // TODO add your handling code here:
    }//GEN-LAST:event_CLEAR_KOMActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();
        MENU a= new MENU();
        a.setVisible(true);
        a.setDefaultCloseOperation(MENU.DISPOSE_ON_CLOSE);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KOMODITAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KOMODITAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KOMODITAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KOMODITAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KOMODITAS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLEAR_KOM;
    private javax.swing.JButton DELETE_KOM;
    private javax.swing.JButton INSERT_KOM;
    private javax.swing.JLabel JUDUL_KOMODITAS;
    private javax.swing.JTextField Kode_Komoditas;
    private javax.swing.JTextField Nilai_Ekspor;
    private javax.swing.JTextField Pangsa_Total;
    private javax.swing.JComboBox<String> Sektor_Komoditas;
    private javax.swing.JTable TabelKomoditas;
    private javax.swing.JButton UPDATE_KOM;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
