/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;


import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author USER
 */
public class PRODUKSI extends javax.swing.JFrame {

    /**
     * Creates new form PRODUKSI
     */
    DefaultTableModel PR;
    public PRODUKSI() {
        initComponents();
        Connect();
        TabelProduksi();
        TabelKomoditas();
        TabelOperator();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Judul_Produksi = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Nama_Operator = new javax.swing.JLabel();
        Sektor_Komo = new javax.swing.JLabel();
        Tahun_Prod = new javax.swing.JLabel();
        Nm_Pod = new javax.swing.JLabel();
        Jml_Prod = new javax.swing.JLabel();
        Jen_Prod = new javax.swing.JLabel();
        SektorKom = new javax.swing.JComboBox<>();
        TahunProd = new javax.swing.JTextField();
        NamaProd = new javax.swing.JTextField();
        JumlProd = new javax.swing.JTextField();
        JenisProd = new javax.swing.JComboBox<>();
        NamaOp = new javax.swing.JComboBox<>();
        satuan = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        INSERT = new javax.swing.JButton();
        UPDATE = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        CLEAR = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelProduksi = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        FilTahun = new javax.swing.JLabel();
        FIlTahProd = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        FilNm = new javax.swing.JLabel();
        FIlNamProd = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        FilKdKom = new javax.swing.JLabel();
        FilJenProd = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        FilJen = new javax.swing.JLabel();
        FilKodKom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Judul_Produksi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Judul_Produksi.setForeground(new java.awt.Color(255, 255, 255));
        Judul_Produksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Judul_Produksi.setText("DATA PRODUKSI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Judul_Produksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Judul_Produksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Nama_Operator.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Nama_Operator.setText("Nama Operator");

        Sektor_Komo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Sektor_Komo.setText("Sektor Komoditas");

        Tahun_Prod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Tahun_Prod.setText("Tahun Produksi");

        Nm_Pod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Nm_Pod.setText("Nama Produksi");

        Jml_Prod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Jml_Prod.setText("Jumlah Produksi");

        Jen_Prod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Jen_Prod.setText("Jenis Produksi");

        JenisProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mentah", "Setengah Jadi", "Jadi" }));

        satuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TON", "KG", "SATUAN", "LITER", "BARREL", " " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sektor_Komo)
                    .addComponent(Tahun_Prod)
                    .addComponent(Nama_Operator))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SektorKom, 0, 191, Short.MAX_VALUE)
                    .addComponent(TahunProd)
                    .addComponent(NamaOp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nm_Pod)
                    .addComponent(Jml_Prod)
                    .addComponent(Jen_Prod))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NamaProd)
                    .addComponent(JenisProd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JumlProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nm_Pod)
                    .addComponent(Nama_Operator)
                    .addComponent(NamaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NamaOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sektor_Komo)
                    .addComponent(Jml_Prod)
                    .addComponent(SektorKom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JumlProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(satuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tahun_Prod)
                    .addComponent(Jen_Prod)
                    .addComponent(TahunProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JenisProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        INSERT.setText("INSERT");
        INSERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INSERTActionPerformed(evt);
            }
        });

        UPDATE.setText("UPDATE");
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });

        DELETE.setText("DELETE");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });

        CLEAR.setText("CLEAR");
        CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(INSERT, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(UPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(CLEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INSERT, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CLEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        TabelProduksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Index", "Kode Operator", "Kode Komoditas", "Tahun Produksi", "Nama Produk", "Jumlah Produksi", "Jenis Produksi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TabelProduksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelProduksiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelProduksi);

        jButton5.setBackground(new java.awt.Color(0, 153, 102));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("MENU");
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(204, 51, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("KELUAR");
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel5.setBackground(new java.awt.Color(0, 153, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        FilTahun.setForeground(new java.awt.Color(255, 255, 255));
        FilTahun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FilTahun.setText("Tahun Produksi");

        FIlTahProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FIlTahProdKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FIlTahProd)
                    .addComponent(FilTahun, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FilTahun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FIlTahProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 153, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        FilNm.setForeground(new java.awt.Color(255, 255, 255));
        FilNm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FilNm.setText("Nama Produk");

        FIlNamProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FIlNamProdKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FilNm, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(FIlNamProd, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FilNm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FIlNamProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 153, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        FilKdKom.setForeground(new java.awt.Color(255, 255, 255));
        FilKdKom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FilKdKom.setText("Jenis Produk");

        FilJenProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "Mentah", "Setengah Jadi", "Jadi" }));
        FilJenProd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FilJenProdItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FilKdKom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FilJenProd, 0, 107, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FilKdKom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FilJenProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(0, 153, 102));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        FilJen.setForeground(new java.awt.Color(255, 255, 255));
        FilJen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FilJen.setText("Kode Komoditas");

        FilKodKom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FilKodKomKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FilJen, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(FilKodKom))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FilJen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FilKodKom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FILTER PRODUK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    String url = "jdbc:sqlserver://192.168.43.36:1433;databaseName=SDAIndo"; /*jadi ip address*/
    String user = "bytadit";
    String password = "bytadit123";
    
    Connection con;
    PreparedStatement pst;
    Statement st;
    ResultSet rs;
    
    public void Connect()
    {
        try {
            con = DriverManager.getConnection(url, user, password);
        } catch (SQLException ex) {
            Logger.getLogger(OPERATOR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void TabelProduksi()
    {
        try {
            pst = con.prepareStatement("SELECT * FROM PRODUKSI");
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData RSM = rs.getMetaData();
            int c;
            c = RSM.getColumnCount();
            
            PR = (DefaultTableModel)TabelProduksi.getModel();
            PR.setRowCount(0);
            
            while(rs.next())
            {
                Vector v2 = new Vector();
                for(int i = 1; i <= c; i++)
                {
                    v2.add(rs.getString("IdProd"));
                    v2.add(rs.getString("Kode_Operator"));
                    v2.add(rs.getString("Kode_Komoditas"));
                    v2.add(rs.getString("Tahun_Produksi"));
                    v2.add(rs.getString("Nama_Produksi"));
                    v2.add(rs.getString("Jumlah_Produksi"));
                    v2.add(rs.getString("Jenis_Produksi"));
                }
                PR.addRow(v2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(OPERATOR.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    private void TabelKomoditas()
    {
        try {
            
            pst = con.prepareStatement("SELECT * FROM KOMODITAS");
            ResultSet rs = pst.executeQuery();
            
            SektorKom.removeAllItems(); 
            
            
            while(rs.next())
            {
                SektorKom.addItem(rs.getString(2));
                
                
            }
        }catch(SQLException ex){
            Logger.getLogger(OPERATOR.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void TabelOperator()
    {
        try {
            
            pst = con.prepareStatement("SELECT * FROM OPERATOR");
            ResultSet rs = pst.executeQuery();
            
            NamaOp.removeAllItems(); 
            
            
            while(rs.next())
            {
                NamaOp.addItem(rs.getString(2));
                
                
            }
        }catch(SQLException ex){
            Logger.getLogger(OPERATOR.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();
        MENU a= new MENU();
        a.setVisible(true);
        a.setDefaultCloseOperation(MENU.DISPOSE_ON_CLOSE);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Apakah anda ingin keluar?", "keluar", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION){
            System.exit(1);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void INSERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INSERTActionPerformed
        
        String Nama_Operator = NamaOp.getSelectedItem().toString();
        String Sektor_Komoditas = SektorKom.getSelectedItem().toString();
        String Tahun_Produksi = TahunProd.getText();
        String Nama_Produk = NamaProd.getText();
        String Jumlah_Produksi = JumlProd.getText();
        String Jenis_Produk = JenisProd.getSelectedItem().toString();
        String Satuan = satuan.getSelectedItem().toString();
        
        try {
            pst = con.prepareStatement("INSERT INTO PRODUKSI SELECT OPERATOR.Kode_Operator, KOMODITAS.Kode_Komoditas, ? AS Tahun_Produksi, ? AS Nama_Produksi, ? AS Jumlah_Produksi, ? AS Jenis_Produksi FROM OPERATOR,KOMODITAS WHERE OPERATOR.Nama_Operator = ? AND KOMODITAS.Sektor_Komoditas = ?;");
            pst.setString(1, Tahun_Produksi);
            pst.setString(2, Nama_Produk);
            pst.setString(3, Jumlah_Produksi);
            pst.setString(4, Jenis_Produk);
            pst.setString(5, Nama_Operator);
            pst.setString(6, Sektor_Komoditas);
            
            
            
            int k = pst.executeUpdate();
            
            if (k==1)
            {
                JOptionPane.showMessageDialog(this,"Data Berhasil Ditambahkan");
                NamaOp.setSelectedItem("");
                SektorKom.setSelectedItem("");
                TahunProd.setText("");
                NamaProd.setText("");
                JumlProd.setText("");
                JenisProd.setSelectedItem("");
                
                NamaOp.requestFocus();
                TabelProduksi();
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Data Gagal Ditambahkan");
            }
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(OPERATOR.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_INSERTActionPerformed

    private void TabelProduksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelProduksiMouseClicked
        DefaultTableModel PR = (DefaultTableModel)TabelProduksi.getModel();
        
        int SelectIndex = TabelProduksi.getSelectedRow();
        
        String ProdId = PR.getValueAt(SelectIndex, 0).toString();
  
        /*NamaOp.setSelectedItem(PR.getValueAt(SelectIndex, 1).toString());*/
        /*SektorKom.setSelectedItem(PR.getValueAt(SelectIndex, 2).toString());*/
        TahunProd.setText(PR.getValueAt(SelectIndex, 3).toString());
        NamaProd.setText(PR.getValueAt(SelectIndex, 4).toString());
        JumlProd.setText(PR.getValueAt(SelectIndex, 5).toString());
        JenisProd.setSelectedItem(PR.getValueAt(SelectIndex, 6).toString());
        
        
        INSERT.setEnabled(false);  
        // TODO add your handling code here:
    }//GEN-LAST:event_TabelProduksiMouseClicked

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
        
        DefaultTableModel PR = (DefaultTableModel)TabelProduksi.getModel();
        int SelectIndex = TabelProduksi.getSelectedRow();
        
        String ProdId = PR.getValueAt(SelectIndex, 0).toString();
         
        String Nama_Operator = NamaOp.getSelectedItem().toString();
        String Sektor_Komoditas = SektorKom.getSelectedItem().toString();
        String Tahun_Produksi = TahunProd.getText();
        String Nama_Produk = NamaProd.getText();
        String Jumlah_Produksi = JumlProd.getText();
        String Jenis_Produk = JenisProd.getSelectedItem().toString();
        String Satuan = satuan.getSelectedItem().toString();
        
        
        try {
            pst = con.prepareStatement("UPDATE PRODUKSI SET Kode_Operator = (SELECT Kode_Operator FROM OPERATOR WHERE Nama_Operator = ?), Kode_Komoditas = (SELECT Kode_Komoditas FROM KOMODITAS WHERE Sektor_Komoditas = ?) , Tahun_Produksi = ?, Nama_Produksi = ?, Jumlah_Produksi = ?, Jenis_Produksi = ? WHERE IdProd = ?");
            
            pst.setString(1, Nama_Operator);
           
            pst.setString(2, Sektor_Komoditas);
            pst.setString(3, Tahun_Produksi);
            pst.setString(4, Nama_Produk);
            pst.setString(5, Jumlah_Produksi);
            pst.setString(6, Jenis_Produk);
            pst.setString(7, ProdId);
            
            int k = pst.executeUpdate();
            
            if (k==1)
            {
                JOptionPane.showMessageDialog(this,"Data Berhasil Diperbarui");
                NamaOp.setSelectedItem("");
                SektorKom.setSelectedItem("");
                TahunProd.setText("");
                NamaProd.setText("");
                JumlProd.setText("");
                JenisProd.setSelectedItem("");
                
                NamaOp.requestFocus();
                TabelProduksi();
                INSERT.setEnabled(true);
                
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Data Gagal Diperbarui");
            }
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(OPERATOR.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_UPDATEActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
        
        DefaultTableModel PR = (DefaultTableModel)TabelProduksi.getModel();
        int SelectIndex = TabelProduksi.getSelectedRow();
        
        String ProdId = PR.getValueAt(SelectIndex, 0).toString();
        
        try {
            pst = con.prepareStatement("DELETE FROM OPERATOR WHERE IdProd = ?");
            
            pst.setString(1, ProdId);
            
            int k = pst.executeUpdate();
            
            if (k==1)
            {
                JOptionPane.showMessageDialog(this,"Data Berhasil Dihapus");
                NamaOp.setSelectedItem("");
                SektorKom.setSelectedItem("");
                TahunProd.setText("");
                NamaProd.setText("");
                JumlProd.setText("");
                JenisProd.setSelectedItem("");
                
                NamaOp.requestFocus();
                TabelProduksi();
                INSERT.setEnabled(true);
                NamaOp.setEnabled(true);
                
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Data Gagal Dihapus");
            }
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(OPERATOR.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_DELETEActionPerformed

    private void CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARActionPerformed
                NamaOp.setSelectedItem("");
                SektorKom.setSelectedItem("");
                TahunProd.setText("");
                NamaProd.setText("");
                JumlProd.setText("");
                JenisProd.setSelectedItem("");
                
                NamaOp.requestFocus();
                INSERT.setEnabled(true);
                TabelProduksi();        // TODO add your handling code here:
    }//GEN-LAST:event_CLEARActionPerformed

    private void filter(String query)
    {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(PR);
        TabelProduksi.setRowSorter(tr);
        
        if(query != "ALL")
        {
            tr.setRowFilter(RowFilter.regexFilter(query));
        }else
        {
            TabelProduksi.setRowSorter(tr);
        }
    }
    private void filter2(String query)
    {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(PR);
        TabelProduksi.setRowSorter(tr);
            tr.setRowFilter(RowFilter.regexFilter(query));
    }
    
        
    private void FIlTahProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FIlTahProdKeyReleased
        String query = FIlTahProd.getText();
        filter2(query);        // TODO add your handling code here:
    }//GEN-LAST:event_FIlTahProdKeyReleased

    private void FIlNamProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FIlNamProdKeyReleased
        String query = FIlNamProd.getText();
        filter2(query);       // TODO add your handling code here:
    }//GEN-LAST:event_FIlNamProdKeyReleased

    private void FilJenProdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FilJenProdItemStateChanged
        String query = FilJenProd.getSelectedItem().toString();
        filter(query);
               // TODO add your handling code here:
    }//GEN-LAST:event_FilJenProdItemStateChanged

    private void FilKodKomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FilKodKomKeyReleased
        
        String query = FilKodKom.getText();
        filter2(query);// TODO add your handling code here:
    }//GEN-LAST:event_FilKodKomKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRODUKSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRODUKSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRODUKSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRODUKSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRODUKSI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLEAR;
    private javax.swing.JButton DELETE;
    private javax.swing.JTextField FIlNamProd;
    private javax.swing.JTextField FIlTahProd;
    private javax.swing.JLabel FilJen;
    private javax.swing.JComboBox<String> FilJenProd;
    private javax.swing.JLabel FilKdKom;
    private javax.swing.JTextField FilKodKom;
    private javax.swing.JLabel FilNm;
    private javax.swing.JLabel FilTahun;
    private javax.swing.JButton INSERT;
    private javax.swing.JLabel Jen_Prod;
    private javax.swing.JComboBox<String> JenisProd;
    private javax.swing.JLabel Jml_Prod;
    private javax.swing.JLabel Judul_Produksi;
    private javax.swing.JTextField JumlProd;
    private javax.swing.JComboBox<String> NamaOp;
    private javax.swing.JTextField NamaProd;
    private javax.swing.JLabel Nama_Operator;
    private javax.swing.JLabel Nm_Pod;
    private javax.swing.JComboBox<String> SektorKom;
    private javax.swing.JLabel Sektor_Komo;
    private javax.swing.JTable TabelProduksi;
    private javax.swing.JTextField TahunProd;
    private javax.swing.JLabel Tahun_Prod;
    private javax.swing.JButton UPDATE;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> satuan;
    // End of variables declaration//GEN-END:variables
}
